# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('code', models.CharField(default=b'##', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'NONE', max_length=20)),
                ('telephone', models.CharField(default=b'NONE', max_length=15)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('area_manager', models.CharField(default=b'NONE', max_length=40)),
                ('area_manager_tel', models.CharField(default=b'NONE', max_length=15)),
                ('store_manager', models.CharField(default=b'NONE', max_length=40)),
                ('store_manager_tel', models.CharField(default=b'NONE', max_length=15)),
                ('trainee_manager', models.CharField(default=b'NONE', max_length=40)),
                ('trainee_manager_tel', models.CharField(default=b'NONE', max_length=15)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchdog.NextInvoice')),
            ],
        ),
    ]
