# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='area_manager',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='area_manager_tel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_manager',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_manager_tel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='store',
            name='trainee_manager',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='trainee_manager_tel',
            field=models.CharField(max_length=15),
        ),
    ]
