# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0002_auto_20180104_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='invoices',
        ),
        migrations.AlterField(
            model_name='nextinvoice',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nextinvoice',
            name='invoice',
            field=models.IntegerField(default=0, primary_key=True),
        ),
    ]
