# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0004_auto_20180104_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nextinvoice',
            old_name='code',
            new_name='code_id',
        ),
    ]
