# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0006_auto_20180104_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextinvoice',
            name='code_id',
        ),
        migrations.AddField(
            model_name='nextinvoice',
            name='code',
            field=models.CharField(default=b'##', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nextinvoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nextinvoice',
            name='invoice',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
