# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0007_auto_20180104_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityCheck',
            fields=[
                ('code', models.CharField(default=b'##', max_length=2, null=True)),
                ('slave', models.IntegerField(default=0, null=True)),
                ('check_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(default=b'NONE', max_length=20)),
            ],
        ),
    ]
