# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0011_remove_yealink_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextinvoice',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchdog.Store'),
        ),
    ]
