# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0015_remove_integritycheck_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
