# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0017_auto_20180118_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
